from ultralytics import YOLO

def evaluate_model():
    # Point to the NEW best weights generated by your training run
    # (Check your 'runs/detect/weapon_detection/v2_cctv_robust' folder)
    model_path = r"D:\Weapon Detection\runs\detect\weapon_detection\yolo26_high_perf\weights\best.pt"
    
    model = YOLO(model_path)

    print("Running Final Exam on the Test split...")

    # Force the model to evaluate ONLY the unseen Test set
    metrics = model.val(
        split='test',         
        imgsz=640,            
        device=0,
        batch=4
    )

    # Output the core metrics
    print("\n--- Final Exam Results ---")
    print(f"Precision: {metrics.box.mp:.3f}")
    print(f"Recall:    {metrics.box.mr:.3f}")
    print(f"mAP50:     {metrics.box.map50:.3f}")
    print(f"mAP50-95:  {metrics.box.map:.3f}")

if __name__ == "__main__":
    evaluate_model()