from ultralytics import YOLO
import numpy as np

def evaluate_model():
    # Point to the NEW best weights generated by your training run
    model_path = r"D:\Weapon Detection\runs\detect\weapon_detection\Final_yolo26n_cctv_aug\weights\best.pt"
    
    model = YOLO(model_path)

    print("Running Final Exam on the Test split...")

    # Force the model to evaluate ONLY the unseen Test set
    metrics = model.val(
        split='test',         
        imgsz=640,            
        device=0,
        batch=4
    )

    # Extract precision and recall
    precision = metrics.box.mp
    recall = metrics.box.mr
    
    # Calculate overall F1-Score (Harmonic Mean of Precision and Recall)
    # The if-condition prevents a division-by-zero error if the model detects nothing
    f1_score = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0

    # Output the core metrics
    print("\n--- Final Exam Results ---")
    print(f"Precision: {precision:.3f}")
    print(f"Recall:    {recall:.3f}")
    print(f"F1-Score:  {f1_score:.3f}")
    print(f"mAP50:     {metrics.box.map50:.3f}")
    print(f"mAP50-95:  {metrics.box.map:.3f}")
    
    # Optional: If you have multiple classes and want the F1-score per class
    # class_f1_scores = metrics.box.f1
    # print(f"Per-Class F1 Scores: {class_f1_scores}")

if __name__ == "__main__":
    evaluate_model()

